<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProfessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('professions')->insert([
        ['name' => 'Acheteur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Administrateur de base de données', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent de sûreté aéroportuaire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent de transit', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent d\'entretien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent funéraire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent immobilier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent de police', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent de presse', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent de sécurité', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agent de surveillance de la voie publique (ASVP)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Agronome', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Ambulancier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Analyste financier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Analyste programmeur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Analyste Web', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Architecte', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Architecte paysagiste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Architecte en système d\'information', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Archiviste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Assistant administratif et financier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Assistant bibliothécaire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Assistant d\'éducation', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Assistant dentaire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Assistant marketing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Assistant paie et administration', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Assistant RH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Assureur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Audioprothésiste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Auditeur financier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Auxiliaire de puériculture', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Auxiliaire de vie sociale', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Avocat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Bibliothécaire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Biologiste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chargé de communication', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chargé de recrutement', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Charpentier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chauffeur de taxi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chefs de chantier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chef de projet', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chef de projet marketing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chef d\'établissement', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chiropracteur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Chirurgien orthopédiste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Coiffeur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Commis de cuisine', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Comptable', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Concepteur de jeux vidéos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Concepteur-rédacteur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Conducteur de grue', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Conducteur de train', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Conseiller', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Conseiller d\'orientation', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Conseiller en insertion professionnelle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Consultant bien-être', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Consultant en informatique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Contrôleur (trains)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Contrôleur aérien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Contrôleur de gestion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Contrôleur financier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Courtier en assurance', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Cuisinier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Décorateur d\'intérieur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Dentiste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Designer industriel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Développeur informatique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Diacre', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Diététicien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Directeur artistique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Directeur des ventes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Directeur financier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Directeur RH', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Économiste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Éducateur de jeunes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Éleveur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Employé de banque', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Enseignant', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Ergothérapeute', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Esthéticienne', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Fleuriste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Gardien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Géomètre', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Gestionnaire immobilier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Hôtesse de l\'air', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Huissier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Illustrateur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Infirmière', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Ingénieur civil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Ingénieur électronicien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Ingénieur du BTP', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Inspecteur de l\'action sanitaire et sociale', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Jardinier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Jardinier paysagiste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Journaliste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Juge', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Kinésithérapeute', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Linguiste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Machiniste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Magasinier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Maître d\'hôtel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Manipulateur radio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Masseur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Mécanicien aéronautique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Médecin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Moniteur d\'auto-école', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Monteur électricien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Nutritionniste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Officier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Opérateur de production', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Opérateur d\'usinage sur commande numérique (UCN)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Opticien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Orthophoniste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Personal Trainer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Pharmacien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Photographe', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Physicien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Physicien médical', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Pilote', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Politicien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Pompier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Poseur de sol (solier)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Prêtre', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Procureur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Professeur des écoles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Professeur d\'éducation physique (EPS)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Professeur de français langue étrangère', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Professeur des universités', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Psychologue', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Réceptionniste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Réceptionniste d\'hôtel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Responsable communication', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Responsable grands comptes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Responsable service clientèle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Sages-femmes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Secrétaire médicale', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Serveur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Skipper', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Soldat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Soudeur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Statisticien', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Surveillant pénitentiaire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Technicien alarme intrusion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Technicien d\'analyses biomédicales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Technicien de maintenance informatique', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Technicien d\'exploitation', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Téléconseiller', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Test manager', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Travailleur social', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Urbaniste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Vendeur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Vétérinaire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
['name' => 'Webmaster', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
]);
    }
}
