<?php
namespace Database\Seeders;
use Carbon\Carbon;
use App\Models\{name};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class VilleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('villes')->insert([
            ['name' => 'Aïn Harrouda', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ben Yakhlef', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bouskoura', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Casablanca', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Médiouna', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Mohammadia', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tit Mellil', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ben Yakhlef', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bejaâd', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ben Ahmed', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Benslimane', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Berrechid', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Boujniba', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Boulanouare', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bouznika', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Deroua', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Borouj', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Gara', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Guisser', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Hattane', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Khouribga', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Loulad', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oued Zem', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Abbou', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad HRiz Sahel', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Mrah', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Saïd', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Sidi Ben Daoud', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ras El Aïn', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Settat', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Rahhal Chataï', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Soualem', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Azemmour', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bir Jdid', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bouguedra', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Echemmaia', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Jadida', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Hrara', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ighoud', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Jamâat Shaim', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Jorf Lasfar', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Khemis Zemamra', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Laaounate', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moulay Abdallah', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oualidia', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Amrane', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Frej', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Ghadbane', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Safi', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sebt El Maârif', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sebt Gzoula', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Ahmed', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Ali Ban Hamdouche', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Bennour', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Bouzid', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Smaïl', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Youssoufia', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Fès', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aïn Cheggag', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bhalil', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Boulemane', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Menzel', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Guigou', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Imouzzer Kandar', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Imouzzer Marmoucha', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Missour', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moulay Yaâcoub', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ouled Tayeb', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Outat El Haj', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ribate El Kheir', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Séfrou', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Skhinate', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tafajight', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Arbaoua', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aïn Dorij', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Dar Gueddari', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Had Kourt', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Jorf El Melha', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kénitra', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Khenichet', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Lalla Mimouna', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Mechra Bel Ksiri', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Mehdia', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moulay Bousselham', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Allal Tazi', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Kacem', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Slimane', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Taibi', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Yahya El Gharb', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Souk El Arbaa', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Akka', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Assa', 'region_id' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bouizakarne', 'region_id' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Ouatia', 'region_id' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Es-Semara', 'region_id' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Fam El Hisn', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Foum Zguid', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Guelmim', 'region_id' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taghjijt', 'region_id' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tan-Tan', 'region_id' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tata', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zag', 'region_id' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Marrakech', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ait Daoud', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Amizmiz', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Assahrij', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Ourir', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ben Guerir', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Chichaoua', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Hanchane', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Kelaâ des Sraghna', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Essaouira', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Fraïta', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ghmate', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ighounane', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Imintanoute', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kattara', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Lalla Takerkoust', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Loudaya', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Lâattaouia', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moulay Brahim', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Mzouda', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ounagha', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sid LMokhtar', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sid Zouin', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Abdallah Ghiat', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Bou Othmane', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Rahhal', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Skhour Rehamna', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Smimou', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tafetachte', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tahannaout', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Talmest', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tamallalt', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tamanar', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tamansourt', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tameslouht', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tanalt', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zeubelemok', 'region_id' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Meknès‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Khénifra', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Agourai', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ain Taoujdate', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' MyAliCherif', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Rissani', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Amalou Ighriben', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aoufous', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Arfoud', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Azrou', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aïn Jemaa', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aïn Karma', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aïn Leuh', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Boubidmane', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Ishaq', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Boudnib', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Boufakrane', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Boumia', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Hajeb', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Elkbab', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Er-Rich', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Errachidia', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Gardmit', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Goulmima', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Gourrama', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Had Bouhssoussen', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Haj Kaddour', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ifrane', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Itzer', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Jorf', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kehf Nsour', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kerrouchen', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Mhaya', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Mrirt', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Midelt', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moulay Ali Cherif', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moulay Bouazza', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moulay Idriss Zerhoun', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moussaoua', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' NZalat Bni Amar', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ouaoumana', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oued Ifrane', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sabaa Aiyoun', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sebt Jahjouh', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Addi', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tichoute', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tighassaline', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tighza', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Timahdite', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tinejdad', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tizguite', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Toulal', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tounfite', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zaouia dIfrane', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zaïda', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ahfir', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aklim', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Al Aroui', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aïn Bni Mathar', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aïn Erreggada', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ben Taïeb', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Berkane', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bni Ansar', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bni Chiker', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bni Drar', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bni Tadjite', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bouanane', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bouarfa', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bouhdila', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Dar El Kebdani', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Debdou', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Douar Kannine', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Driouch', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Aïoun Sidi Mellouk', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Farkhana', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Figuig', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ihddaden', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Jaâdar', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Jerada', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kariat Arekmane', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kassita', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kerouna', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Laâtamna', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Madagh', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Midar', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Nador', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Naima', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oued Heimer', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oujda', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ras El Ma', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Saïdia', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Selouane', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Boubker', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Slimane Echcharaa', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Talsint', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taourirt', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tendrara', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tiztoutine', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Touima', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Touissit', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zaïo', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zeghanghane', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Rabat', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Salé', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ain El Aouda', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Harhoura', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Khémisset', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulmès', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Rommani', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Allal El Bahraoui', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Bouknadel', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Skhirate', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tamesna', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Témara', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tiddas', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tiflet', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Touarga', 'region_id' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Agadir', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Agdz', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Agni Izimmer', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Melloul', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Alnif', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Anzi', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aoulouz', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aourir', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Arazane', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Baha', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Iaâza', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Yalla', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ben Sergao', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Biougra', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Boumalne-Dadès', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Dcheira El Jihadia', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Drargua', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Guerdane', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Harte Lyamine', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ida Ougnidif', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ifri', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Igdamen', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ighil nOumgoun', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Imassine', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Inezgane', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Irherm', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kelaat-MGouna', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Lakhsas', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Lakhsass', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Lqliâa', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Msemrir', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Massa (Maroc)', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Megousse', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ouarzazate', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Berhil', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Teïma', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sarghine', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Ifni', 'region_id' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Skoura', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tabounte', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tafraout', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taghzout', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tagzen', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taliouine', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tamegroute', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tamraght', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tanoumrite Nkob Zagora', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taourirt ait zaghar', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taroudannt', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Temsia', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tifnit', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tisgdal', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tiznit', 'region_id' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Toundoute', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zagora', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Afourar', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aghbala', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Azilal', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Majden', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Beni Ayat', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Béni Mellal', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bin elouidane', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bradia', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bzou', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Dar Oulad Zidouh', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Demnate', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Draa', 'region_id' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Ksiba', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Foum Jamaa', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Fquih Ben Salah', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Kasba Tadla', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ouaouizeght', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Ayad', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad MBarek', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Yaich', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Jaber', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Souk Sebt Oulad Nemma', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zaouïat Cheikh', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tanger‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tétouan‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Akchour', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Assilah', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bab Berred', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bab Taza', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Brikcha', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Chefchaouen', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Dar Bni Karrich', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Dar Chaoui', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Fnideq', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Gueznaia', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Jebha', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Karia', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Khémis Sahel', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ksar El Kébir', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Larache', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Mdiq', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Martil', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Moqrisset', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oued Laou', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oued Rmel', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ouazzane', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Point Cires', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Lyamani', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Sidi Mohamed ben Abdallah el-Raisuni', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Zinat', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ajdir‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aknoul‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Al Hoceïma‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Hichem‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bni Bouayach‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Bni Hadifa‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Ghafsai‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Guercif‎', 'region_id' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Imzouren‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Inahnahen‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Issaguen (Ketama)‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Karia (El Jadida)‎', 'region_id' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Karia Ba Mohamed‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oued Amlil‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oulad Zbair‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tahla‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tala Tazegwaght‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tamassint‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taounate‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Targuist‎', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taza‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Taïnaste‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Thar Es-Souk‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tissa‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tizi Ouasli‎', 'region_id' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Laayoune‎', 'region_id' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' El Marsa‎', 'region_id' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Tarfaya‎', 'region_id' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Boujdour‎', 'region_id' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Awsard', 'region_id' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Oued-Eddahab', 'region_id' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Stehat', 'region_id' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => ' Aït Attab', 'region_id' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
